const P=[['Ulaanbaatar','Mongolia',47.918,106.917],['Dalanzadgad','South Gobi, Mongolia',43.57,104.42],['Sainshand','Dornogovi, Mongolia',44.89,110.14],['Beijing','Northern China',39.90,116.40],['Dunhuang','Gansu, China',40.14,94.66],['Hotan','Taklamakan, China',37.11,79.94],['Aral region','Kazakhstan / Uzbekistan',45,59.5],['Tehran','Iran',35.69,51.39],['Ahvaz','Iran',31.32,48.67],['Baghdad','Iraq',33.31,44.37],['Riyadh','Saudi Arabia',24.71,46.68],['Jaisalmer','Thar Desert, India',26.92,70.90],['Bodélé Depression','Chad',17,18],['Niamey','Niger',13.51,2.11],['Nouakchott','Mauritania',18.08,-15.98],['Dakar','Senegal',14.72,-17.47],['Cairo','Egypt',30.04,31.24],['Tamanrasset','Algeria',22.79,5.52],['Las Palmas','Canary Islands',28.12,-15.44],['Alice Springs','Australia',-23.70,133.88],['El Paso','Texas, USA',31.76,-106.49],['Las Cruces','New Mexico, USA',32.32,-106.77],['Phoenix','Arizona, USA',33.45,-112.07],['Mendoza','Argentina',-32.89,-68.85]];
const C={background:'#95a09a',elevated:'#b98b57',high:'#b96a43',severe:'#934b3b',extreme:'#71372e'};
const $=id=>document.getElementById(id);
const countEl=$('count'),summaryEl=$('summary'),eventsEl=$('events'),nameEl=$('name'),regionEl=$('region'),dustEl=$('dust'),pm10El=$('pm10'),aodEl=$('aod'),noteEl=$('note'),chartEl=$('chart'),storyEl=$('story'),storySourceEl=$('storySource'),sourceTitleEl=$('sourceTitle'),sourceTextEl=$('sourceText'),sourceDistanceEl=$('sourceDistance'),sourceWindEl=$('sourceWind'),sourceNdviEl=$('sourceNdvi'),sourceConfidenceEl=$('sourceConfidence'),searchFormEl=$('searchForm'),locateEl=$('locate'),vegToggleEl=$('vegToggle'),qEl=$('q');
let M=[],D=[],sourceLayers=[],selectedToken=0,ndviLut=null;
const map=L.map('map',{worldCopyJump:true}).setView([28,35],2);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:9,attribution:'&copy; OpenStreetMap'}).addTo(map);
const veg=L.tileLayer.wms('https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi',{layers:'MODIS_Terra_NDVI_8Day',format:'image/png',transparent:true,opacity:.58,version:'1.3.0',attribution:'NASA GIBS MODIS NDVI'});
function sev(x){return x>=500?['extreme','Extreme']:x>=250?['severe','Severe']:x>=100?['high','High']:x>=50?['elevated','Elevated']:['background','Background']}
function fmt(x,d=0){return Number.isFinite(x)?x.toFixed(d):'—'}
function clamp(x,a=0,b=1){return Math.max(a,Math.min(b,x))}
function cardinal(d){if(!Number.isFinite(d))return 'unknown';return ['N','NE','E','SE','S','SW','W','NW'][Math.round(d/45)%8]}
function hav(a,b){const R=6371,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p,q=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function move(lat,lon,bearing,km){const R=6371,p=Math.PI/180,br=bearing*p,d=km/R,la1=lat*p,lo1=lon*p;const la2=Math.asin(Math.sin(la1)*Math.cos(d)+Math.cos(la1)*Math.sin(d)*Math.cos(br));const lo2=lo1+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(la1),Math.cos(d)-Math.sin(la1)*Math.sin(la2));return{lat:la2/p,lon:((lo2/p+540)%360)-180}}
async function current(points){const lat=points.map(x=>x[2]).join(','),lon=points.map(x=>x[3]).join(',');const r=await fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&current=dust,pm10,aerosol_optical_depth&timezone=GMT`);if(!r.ok)throw Error();const j=await r.json();return Array.isArray(j)?j:[j]}
async function load(){let out=[];for(let i=0;i<P.length;i+=12){let ch=P.slice(i,i+12),j=await current(ch);j.forEach((v,k)=>out.push({name:ch[k][0],region:ch[k][1],lat:ch[k][2],lon:ch[k][3],dust:+v.current.dust,pm10:+v.current.pm10,aod:+v.current.aerosol_optical_depth}))}D=out.filter(x=>Number.isFinite(x.dust));render()}
function render(){M.forEach(x=>map.removeLayer(x));M=[];const a=D.filter(x=>x.dust>=50).sort((x,y)=>y.dust-x.dust);countEl.textContent=a.length;summaryEl.textContent=a.length?`${a.length} sampled location${a.length===1?' is':'s are'} above the elevated-dust screening level.`:'No sampled location is currently above the elevated-dust screening level.';eventsEl.innerHTML=a.length?a.slice(0,12).map((x,i)=>`<div class="event" data-i="${i}"><i class="dot" style="background:${C[sev(x.dust)[0]]}"></i><div><strong>${x.name}</strong><br><span>${x.region} · PM₁₀ ${fmt(x.pm10)} µg/m³ · ${sev(x.dust)[1]}</span></div><div class="reading"><b>${fmt(x.dust)}</b><br><span>µg/m³ dust</span></div></div>`).join(''):'<div class="small">No active signal above 50 µg/m³ in the watch network.</div>';document.querySelectorAll('.event').forEach(e=>e.onclick=()=>select(a[+e.dataset.i],true));D.forEach(x=>{if(x.dust<25)return;let s=sev(x.dust)[0],z=Math.max(8,Math.min(20,7+Math.sqrt(x.dust)*.45)),ic=L.divIcon({className:'',html:`<div class="dust-icon" style="width:${z}px;height:${z}px;background:${C[s]};opacity:${x.dust<50?.48:.86}"></div>`,iconSize:[z,z],iconAnchor:[z/2,z/2]});let m=L.marker([x.lat,x.lon],{icon:ic}).addTo(map).bindPopup(`<b>${x.name}</b><br>${fmt(x.dust)} µg/m³ modelled dust`);m.on('click',()=>select(x,false));M.push(m)});if(a[0])select(a[0],false)}
async function select(x,pan){const token=++selectedToken;nameEl.textContent=x.name;regionEl.textContent=x.region;dustEl.textContent=fmt(x.dust);pm10El.textContent=fmt(x.pm10);aodEl.textContent=fmt(x.aod,2);if(pan)map.setView([x.lat,x.lon],5);noteEl.textContent='Loading 72-hour model outlook…';sourceTitleEl.textContent='Tracing likely source…';sourceTextEl.textContent='Following recent low-level winds backward and sampling surface conditions.';sourceDistanceEl.textContent=sourceWindEl.textContent=sourceNdviEl.textContent='—';sourceConfidenceEl.textContent='calculating';storyEl.textContent=`${x.name} currently has ${fmt(x.dust)} µg/m³ of modelled near-surface dust. Checking the winds and upwind surface now.`;try{const [fc,src]=await Promise.all([forecast(x),estimateSource(x)]);if(token!==selectedToken)return;draw(fc.arr);noteEl.textContent=fc.arr.length?`72-hour model peak: ${Math.round(Math.max(...fc.arr))} µg/m³. Not an official warning.`:'No forecast data returned.';renderSource(x,src,fc)}catch(e){console.error(e);if(token!==selectedToken)return;noteEl.textContent='Some event diagnostics are temporarily unavailable.';sourceTitleEl.textContent='Source estimate unavailable';sourceTextEl.textContent='The dust concentration is still shown, but wind or vegetation data could not be retrieved.'}}
async function forecast(x){const r=await fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${x.lat}&longitude=${x.lon}&hourly=dust&forecast_hours=72&timezone=auto`),j=await r.json();return{arr:(j.hourly?.dust||[]).map(Number).filter(Number.isFinite)}}
function draw(a){const ch=chartEl;if(!a.length){ch.innerHTML='<text x="0" y="20" fill="#747b77" font-size="11">No forecast data</text>';return}let mx=Math.max(100,...a),pts=a.map((v,i)=>`${8+i*484/(a.length-1)},${86-v*72/mx}`).join(' ');ch.innerHTML=`<line x1="8" y1="84" x2="492" y2="84" stroke="#dfe3df"/><polyline points="${pts}" fill="none" stroke="#657a6f" stroke-width="2" vector-effect="non-scaling-stroke"/><text x="8" y="12" fill="#747b77" font-size="10">peak ${Math.round(Math.max(...a))} µg/m³</text>`}
async function weatherAt(lat,lon,hoursBack){const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=wind_speed_10m,wind_direction_10m,soil_moisture_0_to_1cm&past_hours=30&forecast_hours=1&wind_speed_unit=ms&timezone=GMT`);if(!r.ok)throw Error('weather');const j=await r.json(),t=j.hourly?.time||[];if(!t.length)throw Error('weather');const target=Date.now()-hoursBack*3600000;let idx=0,best=Infinity;t.forEach((v,i)=>{const d=Math.abs(new Date(v+'Z').getTime()-target);if(d<best){best=d;idx=i}});return{speed:+j.hourly.wind_speed_10m[idx],dir:+j.hourly.wind_direction_10m[idx],moist:+j.hourly.soil_moisture_0_to_1cm[idx]}}
async function loadNdviLut(){if(ndviLut)return ndviLut;try{const r=await fetch('https://gibs.earthdata.nasa.gov/colormaps/v1.3/MODIS_NDVI.xml');const tx=await r.text(),doc=new DOMParser().parseFromString(tx,'text/xml');ndviLut=[...doc.querySelectorAll('ColorMapEntry')].map(e=>{const rgb=(e.getAttribute('rgb')||'').split(',').map(Number),v=e.getAttribute('value')||'';const m=v.match(/\[?(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)/);return rgb.length===3&&m?{rgb,val:(+m[1]+ +m[2])/2}:null}).filter(Boolean);return ndviLut}catch(e){return null}}
async function ndviAt(lat,lon){try{const d=.035,url='https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=MODIS_Terra_NDVI_8Day&STYLES=&FORMAT=image/png&TRANSPARENT=TRUE&SRS=EPSG:4326&WIDTH=3&HEIGHT=3&BBOX='+[lon-d,lat-d,lon+d,lat+d].join(',');const r=await fetch(url),blob=await r.blob(),bmp=await createImageBitmap(blob),cv=document.createElement('canvas');cv.width=cv.height=3;const ctx=cv.getContext('2d');ctx.drawImage(bmp,0,0,3,3);const px=ctx.getImageData(1,1,1,1).data;if(px[3]<20)return null;const lut=await loadNdviLut();if(lut?.length){let best=null,dist=Infinity;for(const e of lut){const q=(e.rgb[0]-px[0])**2+(e.rgb[1]-px[1])**2+(e.rgb[2]-px[2])**2;if(q<dist){dist=q;best=e}}if(best&&dist<1800)return best.val}const greenness=px[1]-(px[0]+px[2])/2;return clamp(.28+greenness/180,-.1,.85)}catch(e){return null}}
async function estimateSource(x){sourceLayers.forEach(l=>map.removeLayer(l));sourceLayers=[];let p={lat:x.lat,lon:x.lon},path=[[x.lat,x.lon]],samples=[];for(let step=0;step<6;step++){const h=step*3,w=await weatherAt(p.lat,p.lon,h),km=clamp(w.speed,0,25)*3*3.6,p2=move(p.lat,p.lon,w.dir,km),nd=await ndviAt(p2.lat,p2.lon),wind=clamp((w.speed-5)/9),dry=Number.isFinite(w.moist)?clamp((.22-w.moist)/.17):.5,bare=Number.isFinite(nd)?clamp((.45-nd)/.38):.5,score=.48*wind+.28*bare+.24*dry;samples.push({lat:p2.lat,lon:p2.lon,w,nd,score,hours:(step+1)*3});path.push([p2.lat,p2.lon]);p=p2}const best=samples.sort((a,b)=>b.score-a.score)[0];const line=L.polyline(path,{color:'#657a6f',weight:2,opacity:.75,dashArray:'5 7'}).addTo(map);sourceLayers.push(line);if(best){const ic=L.divIcon({className:'',html:'<div class="source-icon"></div>',iconSize:[12,12],iconAnchor:[6,6]});const mr=L.marker([best.lat,best.lon],{icon:ic}).addTo(map).bindPopup('<b>Likely source zone</b><br>First-pass surface-wind backtrace');sourceLayers.push(mr)}return{best,path,samples,current:await weatherAt(x.lat,x.lon,0)}}
function renderSource(x,s,fc){if(!s?.best)return;const b=s.best,dist=Math.round(hav({lat:x.lat,lon:x.lon},{lat:b.lat,lon:b.lon})),vegLabel=Number.isFinite(b.nd)?(b.nd<.18?'very sparse':b.nd<.32?'sparse':'moderate'):'unknown',dryLabel=Number.isFinite(b.w.moist)?(b.w.moist<.08?'very dry':b.w.moist<.16?'dry':'moisture present'):'unknown',confidence=b.score>.72?'higher':b.score>.5?'moderate':'low';sourceTitleEl.textContent=`${Math.abs(b.lat).toFixed(1)}°${b.lat>=0?'N':'S'}, ${Math.abs(b.lon).toFixed(1)}°${b.lon>=0?'E':'W'}`;sourceTextEl.textContent=`The strongest candidate along the ${b.hours}-hour surface-wind backtrace is about ${dist} km upwind. The sampled surface is ${vegLabel} vegetation and ${dryLabel}.`;sourceDistanceEl.textContent=dist+' km';sourceWindEl.textContent=fmt(b.w.speed,1)+' m/s';sourceNdviEl.textContent=Number.isFinite(b.nd)?fmt(b.nd,2):'n/a';sourceConfidenceEl.textContent=confidence+' screening confidence';const c=s.current,share=x.pm10>0?Math.round(100*x.dust/x.pm10):null,peak=fc.arr.length?Math.round(Math.max(...fc.arr)):null;storyEl.textContent=`${x.name} is at ${fmt(x.dust)} µg/m³ modelled dust${share!==null?`, about ${share}% of modelled PM₁₀`:''}. Recent surface winds are from the ${cardinal(c.dir)} at ${fmt(c.speed,1)} m/s. The backtrace points toward ${vegLabel} upwind terrain roughly ${dist} km away${peak!==null?`; the 72-hour dust forecast peaks near ${peak} µg/m³`:''}.`;storySourceEl.textContent='Current-event interpretation from CAMS dust, ECMWF winds/soil moisture and MODIS NDVI.'}
async function check(n,r,lat,lon){const[j]=await current([[n,r,lat,lon]]),x={name:n,region:r,lat,lon,dust:+j.current.dust,pm10:+j.current.pm10,aod:+j.current.aerosol_optical_depth};select(x,true)}
searchFormEl.onsubmit=async e=>{e.preventDefault();let q=qEl.value.trim();if(!q)return;try{let r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`),j=await r.json(),p=j.results?.[0];if(!p)throw Error();await check(p.name,[p.admin1,p.country].filter(Boolean).join(', '),p.latitude,p.longitude)}catch(e){alert('Could not find or check that place.')}};
locateEl.onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>check('Your location','Current device location',p.coords.latitude,p.coords.longitude),()=>alert('Location permission was not available.')):alert('Location is not supported in this browser.');
vegToggleEl.onclick=()=>{if(map.hasLayer(veg)){map.removeLayer(veg);vegToggleEl.classList.remove('active')}else{veg.addTo(map);vegToggleEl.classList.add('active')}};
load().catch(()=>summaryEl.textContent='Live data is temporarily unavailable.');setInterval(()=>load().catch(()=>{}),1800000);
